import { describe, expect, it } from "vitest";
import { feedItemToRow, rowToFeedItem } from "@/db/repository";
import type { FeedItemRow } from "@/db/schema";
import type { FeedItem } from "@/types/feed";

const baseItem: FeedItem = {
  id: "hn:123456",
  sourceType: "hackernews",
  sourceName: "Hacker News · someone",
  title: "Show HN: A Cool Project",
  description: "Discussion thread on Hacker News.",
  publishedAt: "2026-09-08T12:00:00.000Z",
  tags: ["Hacker News"],
  score: 42,
  commentCount: 7,
  url: "https://news.ycombinator.com/item?id=123456",
  discussionUrl: "https://news.ycombinator.com/item?id=123456",
};

function rowFromPartial(overrides: Partial<FeedItemRow>): FeedItemRow {
  const now = new Date("2026-09-08T12:05:00.000Z");
  return {
    id: 1,
    sourceKey: "hn:123456",
    sourceType: "hackernews",
    sourceId: null,
    sourceName: "Hacker News · someone",
    title: "Show HN: A Cool Project",
    summary: "Discussion thread on Hacker News.",
    url: "https://news.ycombinator.com/item?id=123456",
    canonicalUrl: "https://news.ycombinator.com/item?id=123456",
    normalizedTitle: "show hn a cool project",
    publishedAt: new Date("2026-09-08T12:00:00.000Z"),
    discussionUrl: "https://news.ycombinator.com/item?id=123456",
    pdfUrl: null,
    score: 42,
    commentCount: 7,
    authors: null,
    tags: ["Hacker News"],
    repositoryFullName: null,
    owner: null,
    language: null,
    stars: null,
    forks: null,
    createdAt: now,
    updatedAt: now,
    lastSeenAt: now,
    // Generated by Postgres (see schema.ts) — never read by rowToFeedItem,
    // but still a real column in a select-star row shape.
    searchVector: null,
    ...overrides,
  };
}

describe("feedItemToRow", () => {
  it("derives canonicalUrl and normalizedTitle deterministically", () => {
    const row = feedItemToRow({
      ...baseItem,
      url: "https://example.com/post?utm_source=newsletter&utm_medium=email",
      title: "Hello,   World!!",
    });

    expect(row.canonicalUrl).toBe("https://example.com/post");
    expect(row.normalizedTitle).toBe("hello world");
  });

  it("maps optional fields to null rather than undefined for the DB layer", () => {
    const row = feedItemToRow(baseItem);
    expect(row.pdfUrl).toBeNull();
    expect(row.repositoryFullName).toBeNull();
    expect(row.authors).toBeNull();
  });

  it("stores empty tags as null instead of an empty array", () => {
    const row = feedItemToRow({ ...baseItem, tags: [] });
    expect(row.tags).toBeNull();
  });

  it("preserves GitHub-specific fields when present", () => {
    const row = feedItemToRow({
      ...baseItem,
      sourceType: "github",
      repositoryFullName: "owner/repo",
      owner: "owner",
      language: "TypeScript",
      stars: 100,
      forks: 10,
    });
    expect(row.repositoryFullName).toBe("owner/repo");
    expect(row.owner).toBe("owner");
    expect(row.language).toBe("TypeScript");
    expect(row.stars).toBe(100);
    expect(row.forks).toBe(10);
  });
});

describe("rowToFeedItem", () => {
  it("round-trips a row back into an equivalent FeedItem", () => {
    const row = rowFromPartial({});
    const item = rowToFeedItem(row);

    expect(item.id).toBe("hn:123456");
    expect(item.sourceType).toBe("hackernews");
    expect(item.title).toBe(baseItem.title);
    expect(item.description).toBe(baseItem.description);
    expect(item.publishedAt).toBe("2026-09-08T12:00:00.000Z");
    expect(item.score).toBe(42);
    expect(item.commentCount).toBe(7);
    expect(item.url).toBe(baseItem.url);
    expect(item.discussionUrl).toBe(baseItem.discussionUrl);
  });

  it("defaults null score/commentCount to 0", () => {
    const item = rowToFeedItem(rowFromPartial({ score: null, commentCount: null }));
    expect(item.score).toBe(0);
    expect(item.commentCount).toBe(0);
  });

  it("omits empty authors/tags arrays rather than returning []", () => {
    const item = rowToFeedItem(rowFromPartial({ authors: [], tags: [] }));
    expect(item.authors).toBeUndefined();
    expect(item.tags).toEqual([]);
  });

  it("converts null optional columns back to undefined", () => {
    const item = rowToFeedItem(rowFromPartial({ pdfUrl: null, sourceId: null }));
    expect(item.pdfUrl).toBeUndefined();
    expect(item.sourceId).toBeUndefined();
  });
});

describe("FeedItem -> row -> FeedItem round trip", () => {
  it("is lossless for the fields it tracks", () => {
    const original: FeedItem = {
      id: "arxiv:2501.12345",
      sourceType: "paper",
      sourceName: "arXiv",
      title: "A Great Paper",
      description: "An abstract.",
      publishedAt: "2026-01-05T00:00:00.000Z",
      tags: ["cs.LG", "cs.AI"],
      score: 0,
      commentCount: 0,
      url: "https://arxiv.org/abs/2501.12345",
      pdfUrl: "https://arxiv.org/pdf/2501.12345",
      authors: ["Alice", "Bob"],
    };

    const row = feedItemToRow(original);
    const roundTripped = rowToFeedItem({
      ...rowFromPartial({}),
      ...row,
      id: 99,
      createdAt: new Date(),
      updatedAt: new Date(),
      lastSeenAt: new Date(),
      publishedAt: new Date(original.publishedAt),
    });

    expect(roundTripped.id).toBe(original.id);
    expect(roundTripped.title).toBe(original.title);
    expect(roundTripped.description).toBe(original.description);
    expect(roundTripped.publishedAt).toBe(original.publishedAt);
    expect(roundTripped.tags).toEqual(original.tags);
    expect(roundTripped.url).toBe(original.url);
    expect(roundTripped.pdfUrl).toBe(original.pdfUrl);
    expect(roundTripped.authors).toEqual(original.authors);
  });
});
