/**
 * Repeatable AI-quality evaluation harness (Step 10). Dev-only, never
 * exposed as a route, never run automatically.
 *
 *   npm run ai:evaluate
 *
 * Flow: select a deterministic ~10-20 item set from persisted real
 * records -> if a provider is configured, run a 1-2 item smoke test ->
 * only on success, evaluate the rest (bounded to the same set) -> write
 * a JSON + Markdown report to artifacts/ai-evaluation/.
 *
 * With no ANTHROPIC_API_KEY configured, this prints what WOULD run and
 * exits — it never fabricates a report from data that was never
 * generated by a real model call.
 */
for (const file of [".env.local", ".env"]) {
  try {
    process.loadEnvFile(file);
  } catch {
    // No such file — fine.
  }
}

import path from "node:path";
import { isDatabaseConfigured } from "@/db";
import { getAiProvider } from "@/lib/ai/provider";
import { PROMPT_VERSION } from "@/lib/ai/prompt";
import { selectEvaluationSet, EVALUATION_BUCKETS } from "@/lib/ai/evaluationSelection";
import { runFullEvaluation, writeEvaluationReport, computeRelevanceStats, computeTopicStats } from "@/lib/ai/evaluationHarness";

const REPORT_DIR = path.join(process.cwd(), "artifacts", "ai-evaluation");

async function main() {
  if (!isDatabaseConfigured()) {
    console.error("DATABASE_URL is not set — the evaluation set is selected from persisted records, so there's nothing to evaluate.");
    process.exitCode = 1;
    return;
  }

  console.log("Selecting deterministic evaluation set...");
  console.log(`Buckets: ${EVALUATION_BUCKETS.map((b) => `${b.label} (up to ${b.limit})`).join(", ")}`);
  const items = await selectEvaluationSet();
  console.log(`Selected ${items.length} item(s) from persisted data.\n`);

  if (items.length === 0) {
    console.log("No persisted items available to evaluate — run ingestion first (visit the app, or run the dev server once).");
    return;
  }

  const provider = getAiProvider();
  console.log("AI provider:", provider ? `configured (${provider.name})` : "not configured");
  console.log("Prompt version:", PROMPT_VERSION);
  console.log("");

  if (!provider) {
    console.log("No ANTHROPIC_API_KEY is configured — real-provider evaluation is PENDING, not run.");
    console.log("The harness itself is fully built and covered by tests using the mock provider (see src/lib/ai/*.test.ts).");
    console.log("No report was written, since a report generated with no real model call would misrepresent quality.");
    return;
  }

  console.log(`Running a smoke test (first 2 of ${items.length} items) before spending calls on the rest...`);
  const result = await runFullEvaluation(items);

  if (result.smokeTestPassed === false) {
    console.error(`Smoke test FAILED: ${result.smokeTestFailureReason ?? "unknown"} — stopping. No further real calls were made.`);
    process.exitCode = 1;
    return;
  }

  if (!result.report) {
    console.error("Evaluation produced no report unexpectedly.");
    process.exitCode = 1;
    return;
  }

  console.log("Smoke test passed. Full evaluation complete.\n");

  const relevance = computeRelevanceStats(result.report);
  const topics = computeTopicStats(result.report);

  console.log(`Items evaluated: ${result.report.itemCount}, real provider calls: ${result.report.realProviderCallCount}`);
  console.log(
    `Tokens: ${result.report.totals.inputTokens} in / ${result.report.totals.outputTokens} out — cost: ${
      result.report.totals.estimatedCostUsd === null ? "unknown" : `$${result.report.totals.estimatedCostUsd.toFixed(5)}`
    }`
  );
  if (relevance.count > 0) {
    console.log(
      `Relevance: min=${relevance.min} max=${relevance.max} mean=${relevance.mean?.toFixed(3)} median=${relevance.median} ` +
        `(high=${relevance.byBand.high} medium=${relevance.byBand.medium} low=${relevance.byBand.low})`
    );
  }
  if (topics.totalTaggedItems > 0) {
    console.log(
      `Topics: avg/item=${topics.averageTopicsPerItem.toFixed(2)}, "Other" rate=${(topics.otherRate * 100).toFixed(0)}%`
    );
  }

  const { jsonPath, mdPath } = await writeEvaluationReport(result.report, REPORT_DIR);
  console.log(`\nReport written to:\n  ${jsonPath}\n  ${mdPath}`);
  console.log("Open the Markdown report and fill in the Human Review columns — factuality/usefulness/topic scores are never auto-filled.");
}

main().catch((error) => {
  console.error("ai:evaluate failed:", error);
  process.exitCode = 1;
});
